Experimenting with Docker

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -44,12 +44,37 @@ mvn package -Dmaven.test.skip=true
 #sudo rm -rf ${CATALINA_HOME}/webapps/ROOT
 cp ./target/prodcatalog.war ${CATALINA_HOME}/webapps
 
-echo "${INFO}Pause for 10sec to let Tomcat redeploy the application.";
+echo "${INFO}Pausing for 10sec to let Tomcat redeploy the application.";
 sleep 10s
 
 # Execute the same functional test as in remote deployment
-sh scripts/test_web_app
+sh scripts/test_web_app 80
 if [[ "$?" -ne 0 ]] ; then
   echo "${ERROR}Push aborted: failed to pass functional tests."; exit $FAILURE
 fi
+
+# Build a new Docker image
+docker build -t prod_catalog_img  .
+# Make sure no previous versions of the container are running
+docker stop prod_catalog_ctr || true
+docker container rm prod_catalog_ctr || true
+# Spin up a new container instance
+docker container run -v ~/.aws/credentials:/root/.aws/credentials:ro -d --name prod_catalog_ctr -p 8081:8080 prod_catalog_img
+
+echo "${INFO}Pausing for 5sec to let Docker spin up the container.";
+sleep 5s
+
+# Execute the same functional test as for the non-containerized version of the app 
+sh scripts/test_web_app 8081
+if [[ "$?" -ne 0 ]] ; then
+  echo "${ERROR}Push aborted: the container has failed to pass functional tests."; exit $FAILURE
+fi
+
+# The image is ready to be pushed to ECR, so tag it
+docker tag prod_catalog_img 691995883950.dkr.ecr.us-west-2.amazonaws.com/prodcatalog_repo:latest
+# Get a fresh ECR auth token
+aws ecr get-login-password | docker login --username AWS --password-stdin 691995883950.dkr.ecr.us-west-2.amazonaws.com
+# Push the image to ECR
+docker push 691995883950.dkr.ecr.us-west-2.amazonaws.com/prodcatalog_repo:latest
+
 exit $SUCCESS
