Removed the colors from the multi-environment scripts

diff --git a/scripts/configure_release b/scripts/configure_release
--- a/scripts/configure_release
+++ b/scripts/configure_release
@@ -1,15 +1,12 @@
 #!/bin/bash
 SUCCESS=0
 FAILURE=1
-ERROR=`tput setaf 1`
-INFO=`tput setaf 2`
-OK=`tput setaf 4`
 
 #
 # This script initializes application configuration data for the release
 #
 if [[ -z "$SERVICE_ENDPOINT_PRODUCT_DETAILS" ]]; then
-  echo "${ERROR}Environment variable SERVICE_ENDPOINT_PRODUCT_DETAILS is not defined."; exit $FAILURE
+  echo "Environment variable SERVICE_ENDPOINT_PRODUCT_DETAILS is not defined."; exit $FAILURE
 else
   echo product_details="$SERVICE_ENDPOINT_PRODUCT_DETAILS" > target/classes/endpoints.properties
 fi
