Added DynamoDB client factory to use local version

diff --git a/scripts/test_web_app b/scripts/test_web_app
--- a/scripts/test_web_app
+++ b/scripts/test_web_app
@@ -1,15 +1,17 @@
 #!/bin/bash
 SUCCESS=0
 FAILURE=1
+ERROR=`tput setaf 1`
+INFO=`tput setaf 7`
 #
 # This script performs a simple functional test agaist the locally deployed application
 #
 result=$(curl -s http://localhost:80/)
 
 if [[ "$result" =~ "Product Catalog" ]]; then
-    echo 'Functional tests passed.'; exit $SUCCESS
+    echo "${INFO}Functional tests passed."; exit $SUCCESS
 else
-    echo 'Functional tests failed for the web content:'
+    echo "${ERROR}Functional tests failed for the web content:"
     echo $result
     exit $FAILURE
 fi
